import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Wrapper } from '@/components/index';
import StoreProvider from './StoreProvider';

import '@gravity-ui/uikit/styles/fonts.css';
import '@gravity-ui/uikit/styles/styles.css';
import './globals.scss';
import styles from './layout.module.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang='ru'>
   <body className={`${styles.root} g-root g-root_theme_dark ${inter.className}`}>
    <StoreProvider>
     <Wrapper>{children}</Wrapper>
    </StoreProvider>
   </body>
  </html>
 );
}
